language: r
dist: bionic
cache: packages

r_github_packages:
  - jtextor/epitope-prediction

script:
  - echo "Prerequisites"
  - make --version
  - wget --version
  - echo "Real work"
  - make

after_success:
  - find .

after_failure:
  - find .

