language: r
dist: bionic
cache: packages

r_github_packages:
  - jtextor/epitope-prediction

before_script:
  - make --version
  - wget --version

script:
  - make

after_success:
  - find . | egrep -v "\.git"


after_failure:
  - find . | egrep -v "\.git"

