language: r
dist: bionic
cache: packages

r_github_packages:
  - jtextor/epitope-prediction

before_script:
  - make --version
  - wget --version
  - wget richelbilderbeek.nl/index.htm ; cat index.htm; rm index.htm

script:
  - make test
  - make

after_success:
  - find . | egrep -v "\.git"


after_failure:
  - find . | egrep -v "\.git"

